package programfinal;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

public class Saraly1 extends javax.swing.JFrame {
    private Connection con = null;
    private ResultSet rs = null;
    private PreparedStatement pst = null;
    /**
     * Creates new form Saraly1
     */
    public Saraly1() {
        initComponents();
        con = Connect.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panel4 = new java.awt.Panel();
        panel11 = new java.awt.Panel();
        label1 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        panel12 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        panel13 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        OT = new javax.swing.JTextField();
        Salary = new javax.swing.JTextField();
        panel14 = new java.awt.Panel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Exp = new javax.swing.JTextField();
        SS = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Tax = new javax.swing.JTextField();
        panel15 = new java.awt.Panel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TotalIncome = new javax.swing.JTextField();
        panel16 = new java.awt.Panel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TotalDeduct = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Print = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        EMP = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        ButS = new javax.swing.JButton();
        Cal = new javax.swing.JButton();
        Pos = new javax.swing.JTextField();
        Net = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        SurN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 227, 231));

        jPanel2.setBackground(new java.awt.Color(81, 196, 211));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Salary Bill");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(351, 351, 351))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(19, 44, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panel4.setBackground(new java.awt.Color(19, 44, 51));
        panel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel4.setForeground(new java.awt.Color(25, 26, 24));
        panel4.setLayout(new java.awt.BorderLayout());

        panel11.setBackground(new java.awt.Color(18, 110, 130));

        label1.setText("label1");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(216, 227, 231));
        jLabel2.setText("Income");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout panel11Layout = new javax.swing.GroupLayout(panel11);
        panel11.setLayout(panel11Layout);
        panel11Layout.setHorizontalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel11Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel2)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        panel11Layout.setVerticalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel12.setBackground(new java.awt.Color(18, 110, 130));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(216, 227, 231));
        jLabel3.setText("Deduct income");

        javax.swing.GroupLayout panel12Layout = new javax.swing.GroupLayout(panel12);
        panel12.setLayout(panel12Layout);
        panel12Layout.setHorizontalGroup(
            panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel12Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel3)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        panel12Layout.setVerticalGroup(
            panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        panel13.setBackground(new java.awt.Color(18, 110, 130));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(216, 227, 231));
        jLabel4.setText("Labor / Salary");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(216, 227, 231));
        jLabel5.setText("Bath");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(216, 227, 231));
        jLabel6.setText("OverTime");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(216, 227, 231));
        jLabel7.setText("HR");

        OT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        OT.setText("0");
        OT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OTMouseClicked(evt);
            }
        });
        OT.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                OTInputMethodTextChanged(evt);
            }
        });
        OT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTActionPerformed(evt);
            }
        });

        Salary.setBackground(new java.awt.Color(18, 110, 130));
        Salary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Salary.setForeground(new java.awt.Color(255, 255, 255));
        Salary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Salary.setText("0");
        Salary.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel13Layout = new javax.swing.GroupLayout(panel13);
        panel13.setLayout(panel13Layout);
        panel13Layout.setHorizontalGroup(
            panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel13Layout.createSequentialGroup()
                        .addComponent(Salary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(panel13Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(OT, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        panel13Layout.setVerticalGroup(
            panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(OT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        panel14.setBackground(new java.awt.Color(18, 110, 130));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(216, 227, 231));
        jLabel8.setText("Expense");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(216, 227, 231));
        jLabel9.setText("Bath");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(216, 227, 231));
        jLabel10.setText("Social security");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(216, 227, 231));
        jLabel11.setText("Bath");

        Exp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Exp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Exp.setText("0");
        Exp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpMouseClicked(evt);
            }
        });
        Exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpActionPerformed(evt);
            }
        });

        SS.setBackground(new java.awt.Color(18, 110, 130));
        SS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SS.setForeground(new java.awt.Color(255, 255, 255));
        SS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        SS.setText("0");
        SS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(216, 227, 231));
        jLabel16.setText("Tax");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(216, 227, 231));
        jLabel17.setText("Bath");

        Tax.setBackground(new java.awt.Color(18, 110, 130));
        Tax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tax.setForeground(new java.awt.Color(255, 255, 255));
        Tax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Tax.setText("0");
        Tax.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel14Layout = new javax.swing.GroupLayout(panel14);
        panel14.setLayout(panel14Layout);
        panel14Layout.setHorizontalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel14Layout.createSequentialGroup()
                        .addGroup(panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel14Layout.createSequentialGroup()
                                .addComponent(Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(panel14Layout.createSequentialGroup()
                                .addComponent(SS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))))
                    .addGroup(panel14Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addGap(18, 18, 18))
        );
        panel14Layout.setVerticalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel14Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(SS, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(Exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        panel15.setBackground(new java.awt.Color(18, 110, 130));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(216, 227, 231));
        jLabel12.setText("Total");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(216, 227, 231));
        jLabel13.setText("Bath");

        TotalIncome.setBackground(new java.awt.Color(18, 110, 130));
        TotalIncome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TotalIncome.setForeground(new java.awt.Color(255, 255, 255));
        TotalIncome.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TotalIncome.setText("0");
        TotalIncome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TotalIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalIncomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel15Layout = new javax.swing.GroupLayout(panel15);
        panel15.setLayout(panel15Layout);
        panel15Layout.setHorizontalGroup(
            panel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TotalIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        panel15Layout.setVerticalGroup(
            panel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel15Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(TotalIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        panel16.setBackground(new java.awt.Color(18, 110, 130));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(216, 227, 231));
        jLabel15.setText("Total");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(216, 227, 231));
        jLabel14.setText("Bath");

        TotalDeduct.setBackground(new java.awt.Color(18, 110, 130));
        TotalDeduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TotalDeduct.setForeground(new java.awt.Color(255, 255, 255));
        TotalDeduct.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TotalDeduct.setText("0");
        TotalDeduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TotalDeduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalDeductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel16Layout = new javax.swing.GroupLayout(panel16);
        panel16.setLayout(panel16Layout);
        panel16Layout.setHorizontalGroup(
            panel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TotalDeduct, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18))
        );
        panel16Layout.setVerticalGroup(
            panel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel16Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(TotalDeduct, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Employee code :");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Name :");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Position :");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("Net money :");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setText("Bath");

        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        jButton2.setText("Main Meun");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        EMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMPActionPerformed(evt);
            }
        });

        Name.setBackground(java.awt.Color.lightGray);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        ButS.setText("Search");
        ButS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSActionPerformed(evt);
            }
        });

        Cal.setText("Cal");
        Cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalActionPerformed(evt);
            }
        });

        Pos.setBackground(java.awt.Color.lightGray);
        Pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosActionPerformed(evt);
            }
        });

        Net.setBackground(new java.awt.Color(216, 227, 231));
        Net.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Net.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Net.setText("0");
        Net.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Net.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setText("Surname :");

        SurN.setBackground(java.awt.Color.lightGray);
        SurN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EMP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButS)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SurN, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(Net, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addGap(52, 52, 52)
                        .addComponent(Cal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(EMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(SurN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButS, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26)
                    .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Net, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Menu1 M = new Menu1();
        M.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    private void ShowData(){
        String sql = "select*from Employee";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                System.out.println(rs.getString("Name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Saraly1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void EMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMPActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_EMPActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NameActionPerformed

    private void ButSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSActionPerformed
        // TODO add your handling code here:
        try {
            String sql= "select*from Employee where EmployeeCode='"+EMP.getText()+"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();//เก็บข้อมูลของแต่ละแถวในแต่ละฐานข้อมูลไว้
            if(rs.first()){
            Name.setText(rs.getString("Name"));
            Name.setEditable(false);
            SurN.setText(rs.getString("Surname"));
            SurN.setEditable(false);
            Pos.setText(rs.getString("Position"));
            Pos.setEditable(false);
            Salary.setText(rs.getString("Salary"));
            Salary.setEditable(false);
            double n1 = Double.parseDouble(Salary.getText());
            double SumS = n1*0.01;
            
            DecimalFormat df = new DecimalFormat();
            df.setMaximumFractionDigits(2);
            String s = df.format(SumS);
            SS.setText(s);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Saraly1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButSActionPerformed

    private void CalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalActionPerformed
        // TODO add your handling code here:
        //-----
        
        //+++++
        double n2 = Double.parseDouble(Salary.getText());
        double n3 = Double.parseDouble(Exp.getText());
        double n4 = Double.parseDouble(OT.getText());
        double OverTime = n4*42;
        double SumIncome = OverTime+n2;
        double NetMoney = 0;       
        double Paid = 0;
        
        
        if(n2 >= 0 && n2<=150000){
            NetMoney = n2-n3-(2500*0.5);
            Paid = NetMoney*0;

        }
        else if(n2>150000 && n2<=300000){
            NetMoney = n2-n3-(5000*0.5);
            Paid = NetMoney*0.05;
        }
        else if(n2>300000 && n2<=500000){
            NetMoney = n2-n3-(7500*0.5);
            Paid = NetMoney*0.1;
        }
        else if(n2>500000 && n2<=750000){
            NetMoney = n2-n3-(10000*0.5);
            Paid = NetMoney*0.15;
            
        }
        else if(n2>750000 && n2<=1000000){
            NetMoney = n2-n3-(12500*0.5);
            Paid = NetMoney*0.20;
            
        }
        else if(n2>1000000 && n2<=2000000){
            NetMoney = n2-n3-(15000*0.5);
            Paid = NetMoney*0.25;
            
        }
        else if(n2>2000000 && n2<=5000000){
            NetMoney = n2-n3-(20000*0.5);
            Paid = NetMoney*0.30;
            
        }
        else if(n2>5000000){
            NetMoney = n2-n3-(25000*0.5);
            Paid = NetMoney*0.35;
            
        }
        
        DecimalFormat df = new DecimalFormat();
            df.setMaximumFractionDigits(2);
            String s = df.format(Paid);
            String TI = df.format(SumIncome);
            Tax.setText(s);
            TotalIncome.setText(TI);
            double SumS = n2*0.01;
            String A = df.format(SumS);
            SS.setText(A);
            double SumDeduct = SumS+Paid;
            String SD = df.format(SumDeduct);
            TotalDeduct.setText(SD);
            double FinalNet = SumIncome-SumDeduct;
            String FN = df.format(FinalNet);
            Net.setText(FN);
            
            
        
    }//GEN-LAST:event_CalActionPerformed

    private void PosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PosActionPerformed

    private void ExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpActionPerformed

    private void OTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OTActionPerformed

    private void SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryActionPerformed

    private void SSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSActionPerformed

    private void TotalIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalIncomeActionPerformed

    private void TotalDeductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalDeductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalDeductActionPerformed

    private void NetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NetActionPerformed

    private void SurNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SurNActionPerformed

    private void TaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaxActionPerformed

    private void OTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OTMouseClicked
        // TODO add your handling code here:
        OT.setText("");
    }//GEN-LAST:event_OTMouseClicked

    private void ExpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpMouseClicked
        // TODO add your handling code here:
        Exp.setText("");
    }//GEN-LAST:event_ExpMouseClicked

    private void OTInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_OTInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_OTInputMethodTextChanged

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        
        Document doc = new Document();
        try {
      
            PdfWriter.getInstance(doc, new FileOutputStream("TableCellBorder.pdf"));
            doc.open();

            PdfPTable table = new PdfPTable(3);
            PdfPTable table2 = new PdfPTable(2);
            PdfPCell cell1 = new PdfPCell(new Phrase(""));
            cell1.setUseBorderPadding(true);
            

            // Setting cell's border width and color
            cell1.setBorderWidth(5f);
            cell1.setBorderColor(BaseColor.WHITE);
            table.addCell(cell1);

            PdfPCell cell2 = new PdfPCell(new Phrase("Salary slip"));
            
            cell2.setUseBorderPadding(true);

            // Setting cell's background color
            cell2.setBorderColor(BaseColor.WHITE);
            cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            // Setting cell's individual border color
            //cell2.setBorderWidthTop(1f);
            //cell2.setBorderColorTop(BaseColor.RED);
            //cell2.setBorderColorRight(BaseColor.GREEN);
            //cell2.setBorderColorBottom(BaseColor.BLUE);
            //cell2.setBorderColorLeft(BaseColor.BLACK);
            table.addCell(cell2);

            PdfPCell cell3 = new PdfPCell(new Phrase(""));
            cell3.setUseBorderPadding(true);
            cell3.setBorderColor(BaseColor.WHITE);
            // Setting cell's individual border width
            //cell3.setBorderWidthTop(2f);
            //cell3.setBorderWidthRight(1f);
            //cell3.setBorderWidthBottom(2f);
            //cell3.setBorderWidthLeft(1f);
            table.addCell(cell3);
            
            PdfPCell cell4 = new PdfPCell(new Phrase(""));
            cell4.setUseBorderPadding(true);

            // Setting cell's border width and color
            cell4.setBorderWidth(5f);
            cell4.setBorderColor(BaseColor.WHITE);
            table.addCell(cell4);
            
            
            
            PdfPCell cell5 = new PdfPCell(new Phrase(""));
            cell5.setUseBorderPadding(true);

            // Setting cell's border width and color
            cell5.setBorderWidth(5f);
            cell5.setBorderColor(BaseColor.WHITE);
            table.addCell(cell5);
            
            PdfPCell cell6 = new PdfPCell(new Phrase(""));
            cell6.setUseBorderPadding(true);

            // Setting cell's border width and color
            cell6.setBorderWidth(5f);
            cell6.setBorderColor(BaseColor.WHITE);
            table.addCell(cell6);
            table.completeRow();
            
            
            
            PdfPCell cell7 = new PdfPCell(new Phrase("Company\n"));
            
            cell7.setUseBorderPadding(true);

            // Setting cell's background color
            cell7.setBorderColor(BaseColor.WHITE);
            cell7.setHorizontalAlignment(Element.ALIGN_LEFT);         
            table.addCell(cell7);

            PdfPCell cell8 = new PdfPCell(new Phrase(""));
            cell8.setUseBorderPadding(true);
            cell8.setBorderColor(BaseColor.WHITE);
            cell8.setFixedHeight(50);
            table.addCell(cell8);
            
            PdfPCell cell9 = new PdfPCell(new Phrase(""));
            cell9.setUseBorderPadding(true);
            cell9.setHorizontalAlignment(Element.ALIGN_RIGHT);
            // Setting cell's border width and color
            cell9.setBorderColor(BaseColor.WHITE);
            table.addCell(cell9);
            table.completeRow();
            
            PdfPCell cell10 = new PdfPCell(new Phrase("\nIncome"));
            
            cell10.setUseBorderPadding(true);

            // Setting cell's background color
            cell10.setBorderColor(BaseColor.BLACK);
            cell10.setHorizontalAlignment(Element.ALIGN_CENTER);         
            table2.addCell(cell10);

            PdfPCell cell11 = new PdfPCell(new Phrase("\nDeduct income"));
            cell11.setUseBorderPadding(true);
            cell11.setBorderColor(BaseColor.BLACK);
            cell11.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell11.setFixedHeight(50);
            table2.addCell(cell11);
            table2.completeRow();
            //PdfPCell cell12 = new PdfPCell(new Phrase(""));
            //cell12.setUseBorderPadding(true);
            //cell12.setHorizontalAlignment(Element.ALIGN_RIGHT);
            // Setting cell's border width and color
            //cell12.setBorderColor(BaseColor.BLACK);
            //table.addCell(cell9);
            
            
            PdfPCell cell13 = new PdfPCell(new Phrase("\n Salary"));
            
            cell13.setUseBorderPadding(true);

            // Setting cell's background color
            cell13.setBorderColor(BaseColor.BLACK);
            cell13.setHorizontalAlignment(Element.ALIGN_MIDDLE);         
            table2.addCell(cell13);

            PdfPCell cell14 = new PdfPCell(new Phrase("\n Social security"));
            cell14.setUseBorderPadding(true);
            cell14.setBorderColor(BaseColor.BLACK);
            cell14.setHorizontalAlignment(Element.ALIGN_MIDDLE);
            cell14.setFixedHeight(200);
            table2.addCell(cell14);
            
            //PdfPCell cell15 = new PdfPCell(new Phrase(""));
            //cell15.setUseBorderPadding(true);
            //cell15.setHorizontalAlignment(Element.ALIGN_RIGHT);
            // Setting cell's border width and color
            //cell15.setBorderColor(BaseColor.BLACK);
            //table.addCell(cell15);
            table2.completeRow();
            
            
            doc.add(table);
            doc.add(table2);
        } catch (DocumentException | FileNotFoundException e) {
            e.printStackTrace();
            
        } finally {
            doc.close();
        }
    
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saraly1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saraly1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saraly1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saraly1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saraly1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButS;
    private javax.swing.JButton Cal;
    private javax.swing.JTextField EMP;
    private javax.swing.JTextField Exp;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Net;
    private javax.swing.JTextField OT;
    private javax.swing.JTextField Pos;
    private javax.swing.JButton Print;
    private javax.swing.JTextField SS;
    private javax.swing.JTextField Salary;
    private javax.swing.JTextField SurN;
    private javax.swing.JTextField Tax;
    private javax.swing.JTextField TotalDeduct;
    private javax.swing.JTextField TotalIncome;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private java.awt.Label label1;
    private java.awt.Panel panel11;
    private java.awt.Panel panel12;
    private java.awt.Panel panel13;
    private java.awt.Panel panel14;
    private java.awt.Panel panel15;
    private java.awt.Panel panel16;
    private java.awt.Panel panel4;
    // End of variables declaration//GEN-END:variables
}
